name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code 
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Cache pip dependescies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        
      - name: update pip 
        run: |
          pip install --upgrade pip

      - name: install dependescies
        run: |
          pip install -r requirements.txt

      - name: run pipeline
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        run: |
          dvc repro
      
      - name: run model tests
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m unittest tests/test_model.py
      
      - name: promote model 
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: | 
          python src/models/promote_model.py
      
      - name: run fastapi test
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: | 
          python -m unittest tests/test_fastapi.py
      
      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set default.region "ap-south-1"
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 851725541946.dkr.ecr.ap-south-1.amazonaws.com
      
      - name: build docker image
        run: |
          docker build -t autonexus_ecr_image .
      
      - name: tag docker autonexus_ecr_image
        run: |
          docker tag autonexus_ecr_image:latest 851725541946.dkr.ecr.ap-south-1.amazonaws.com/autonexus_ecr_image:latest
      
      - name: push docker image to ECR
        run: |
          docker push 851725541946.dkr.ecr.ap-south-1.amazonaws.com/autonexus_ecr_image:latest
      
      - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region ap-south-1
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 851725541946.dkr.ecr.ap-south-1.amazonaws.com
            docker pull 851725541946.dkr.ecr.ap-south-1.amazonaws.com/autonexus_ecr_image:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 80:8000 -e DAGSHUB_PAT=${{ secrets.DAGSHUB_PAT }} --name my-app 851725541946.dkr.ecr.ap-south-1.amazonaws.com/autonexus_ecr_image:latest